---
title: BibleBot
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: A Discord bot for Bible verses
description: A Discord bot for Bible verses
url: https://biblebot.vypr.space
baseurl: 
author:
  name: Elliott Pardee
  url: https://vypr.space
  email: vypr@vypr.space
